### ISSUE TITLE
Text problem

### ISSUE THREAD

**Issue by ghost** [cyneprepou4uk/Captain-Tsubasa-2-Translation#1]
Hi , amazing efforts 

I want to share that, I did assemble using the batch file included, Intro text was fine till this happened :
![image](https://user-images.githubusercontent.com/37517008/89700163-caef8900-d923-11ea-9e15-6ad705875f29.png)

**Comment by cyneprepou4uk** [comment]
Hi, thanks. It is not translated yet, don't worry about it :)
