### ISSUE TITLE
Awesome dissam but...

### ISSUE THREAD

**Issue by turric4n** [cyneprepou4uk/Captain-Tsubasa-2-Translation#2]
Your work is excellent, but I am disappointed to see that all of the ASM labels and comments are written in Cyrillic. Is there a particular reason for this choice?

**Comment by cyneprepou4uk** [comment]
Yes. I speak Russian, so that's why.

**Comment by turric4n** [comment]
I would like to contribute to the project, but the language barrier is making it difficult for me. I am interested in learning CT2 code, but the fact that it is written in Russian is making it challenging for me.

**Comment by iromhacker** [comment]
If you want to contribute with translation, there is a link to Google Docs in Readme. I don't need help with technical hacking stuff.

And about you learning CT2 code, I can't help with that. You can use one of the earliest commits, there shouldn't be many Russian words,

**Comment by cyneprepou4uk** [comment]
If you want to contribute with translation, there is a link to Google Docs in Readme. I don't need help with technical hacking stuff.

And about you learning CT2 code, I can't help with that. You can use one of the earliest commits, there shouldn't be many Russian words,
